# Rename file to application.yml

server:
  port: # port of your application

dev-mode:

# database configuration
spring:
  jpa:
    hibernate:
      ddl-auto: # create-drop - will drop your database every time when you start application
                # update will - only update your database
  datasource:
    url: # example for postgre: "jdbc:postgresql://localhost:5432/socialNetwork", where socialNetwork name of database
    username: # database username
    password: # database password

# JWT configuration
jwt:
  secret: # secret word for encrypting jwt token
  expirationTimeInSeconds: # expiration time for jwt token in seconds
  headerFiledName: # Header field name for token